# Generated by Django 4.1.7 on 2023-04-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
