# Generated by Django 4.1.7 on 2023-04-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_usuario_imagem_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_img/%Y/%m/%d'),
        ),
    ]
