# Generated by Django 4.1.7 on 2023-06-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0010_alter_categoria_cursos'),
        ('conta', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cursos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cursos_aprovados',
            field=models.ManyToManyField(blank=True, to='curso.curso'),
        ),
    ]
