# Generated by Django 4.1.7 on 2023-03-19 22:17

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_usuario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=cpf_field.models.CPFField(default=1, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
