# Generated by Django 4.1.7 on 2023-04-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_solicitacao_curso'),
        ('conta', '0005_alter_usuario_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='home.curso'),
        ),
    ]
