# Generated by Django 4.1.7 on 2023-03-30 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0005_alter_token_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='token',
            name='validou',
            field=models.BooleanField(default=False),
        ),
    ]
