# Generated by Django 4.1.7 on 2023-03-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0006_token_data_criacao_token_validou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
