version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/app
    expose:
      - 8000
    env_file:
      - .env
    command: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:latest
    restart: always
    volumes:
    - ./nginx:/etc/nginx/conf.d
    - ./staticfiles:/app/static

    ports:
      - 8080:80
    depends_on:
      - web
