version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    expose:
      - 8000

  certbot:
    image: certbot/certbot
    volumes:
      - static_volume:/code/staticfiles
    entrypoint: sh -c "sleep 3600" # Keep the container running indefinitely

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    command: >
      sh -c "
        if [ -f /etc/nginx/nginx.conf ]; then
          sed -i 's/# SSL configuration/ssl_certificate \/etc\/letsencrypt\/live\/eadscientia.com.br\/fullchain.pem;\n    ssl_certificate_key \/etc\/letsencrypt\/live\/eadscientia.com.br\/privkey.pem;\n    ssl_trusted_certificate \/etc\/letsencrypt\/live\/eadscientia.com.br\/chain.pem;\n    ssl_dhparam \/etc\/letsencrypt\/live\/eadscientia.com.br\/dhparam.pem;\n\n    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_prefer_server_ciphers on;\n    ssl_ciphers \"EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH\";\n    ssl_ecdh_curve secp384r1;\n    ssl_session_cache shared:SSL:10m;\n    ssl_session_timeout 1d;\n    ssl_session_tickets off;\n\n    ssl_stapling on;\n    ssl_stapling_verify on;\n    resolver 8.8.8.8 8.8.4.4 valid=300s;\n    resolver_timeout 5s;\n\n    add_header Strict-Transport-Security \"max-age=63072000; includeSubDomains; preload\";\n    add_header Content-Security-Policy \"default-src https:; script-src https:; style-src https:; img-src https: data:; font-src https: data:\";\n    add_header X-Frame-Options DENY;\n    add_header X-Content-Type-Options nosniff;\n    add_header X-XSS-Protection \"1; mode=block\";'
        fi
        nginx -g 'daemon off;'
      "

    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  letsencrypt:
