services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf  # Atualizado para usar o arquivo nginx.conf
      - ./staticfiles:/app/staticfiles
    ports:
      - "8080:80"
    depends_on:
      - web
