version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/html --email matheusarrow28@gmail.com --agree-tos --no-eff-email -d eadscientia.com.br


volumes:
  static_volume:
  media_volume:
