version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - /home/TCS/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
