version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - django
