# Estágio de produção
FROM nginx:latest

# Copia os arquivos estáticos da pasta local para o diretório do Nginx
COPY staticfiles /usr/share/nginx/html

# Copia o arquivo de configuração do Nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expõe a porta 80 para o Nginx
EXPOSE 80

# Inicia o servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
