# Generated by Django 4.1.7 on 2023-04-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='curso',
        ),
    ]
