# Generated by Django 4.1.7 on 2023-04-07 21:33

import cpf_field.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='cpf',
            field=cpf_field.models.CPFField(default=1, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_solicitacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
