# Generated by Django 4.1.7 on 2023-04-09 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_solicitacao_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.curso'),
            preserve_default=False,
        ),
    ]
