# Generated by Django 4.1.7 on 2023-04-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_solicitacao_cpf_solicitacao_data_solicitacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='telefone',
        ),
    ]
