# Generated by Django 4.1.7 on 2023-04-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_solicitacao_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
