# Generated by Django 4.1.7 on 2023-04-08 20:11

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_solicitacao_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
