# Generated by Django 4.1.7 on 2023-04-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulocurso',
            name='video',
        ),
        migrations.AddField(
            model_name='videocurso',
            name='modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curso.modulocurso'),
            preserve_default=False,
        ),
    ]
