# Generated by Django 4.1.7 on 2023-06-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='videos',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='videos',
            field=models.ManyToManyField(to='curso.video'),
        ),
    ]
