# Generated by Django 4.1.7 on 2023-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_capitulo_autor_video_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(default='curso/img/curso.png', upload_to='categoria/img')),
                ('cursos', models.ManyToManyField(to='curso.curso')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categoria',
                'db_table': 'categoria',
            },
        ),
    ]
