# Generated by Django 4.1.7 on 2023-05-13 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_video_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='autor',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('videos', models.ManyToManyField(to='curso.video')),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
                'db_table': 'capitulo',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='capitulos',
            field=models.ManyToManyField(to='curso.capitulo'),
        ),
    ]
