# Generated by Django 4.1.7 on 2023-05-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_video_options_remove_video_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(),
        ),
    ]
