# Generated by Django 4.1.7 on 2023-06-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='img',
            field=models.ImageField(default='curso/img/curso.png', upload_to='categoria/%Y/%m/%d'),
        ),
    ]
