# Generated by Django 4.1.7 on 2023-06-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_categoria_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='img',
            field=models.ImageField(default='curso/img/curso.png', upload_to='curso/%Y/%m/%d'),
        ),
    ]
