# Generated by Django 4.1.7 on 2023-05-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='img',
            field=models.ImageField(default='curso/img/curso.png', upload_to='curso/img'),
        ),
    ]
