# Generated by Django 4.1.7 on 2023-06-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_alter_curso_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img_mini',
            field=models.ImageField(default='curso/img/curso.png', upload_to='categoria/%Y/%m/%d'),
        ),
    ]
