# Generated by Django 4.1.7 on 2023-06-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_categoria_img_mini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='img_mini',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='img',
            field=models.FileField(default='curso/img/curso.png', upload_to='categoria/%Y/%m/%d'),
        ),
    ]
