# Generated by Django 4.1.7 on 2023-06-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0009_alter_categoria_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='curso.curso'),
        ),
    ]
