# Generated by Django 4.1.7 on 2023-06-10 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0011_aprovadocursousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovadocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 20, 44, 2, 303613)),
        ),
        migrations.AlterField(
            model_name='aprovadocursousuario',
            name='quantidade_assitido',
            field=models.IntegerField(),
        ),
    ]
