# Generated by Django 4.1.7 on 2023-06-18 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0012_alter_acessocursousuario_data_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 17, 54, 10, 130016)),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=100),
        ),
    ]
