# Generated by Django 4.1.7 on 2023-06-11 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0012_alter_aprovadocursousuario_data_termino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duracao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aprovadocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 15, 46, 51, 97361)),
        ),
    ]
