# Generated by Django 4.1.7 on 2023-06-25 20:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0015_alter_acessocursousuario_data_termino_solicitarcurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'alternativa',
                'verbose_name_plural': 'alternativas',
                'db_table': 'alternativa',
            },
        ),
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 17, 49, 51, 773204)),
        ),
        migrations.AlterField(
            model_name='solicitarcurso',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 17, 49, 51, 773204)),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enuciado', models.CharField(max_length=250)),
                ('resposta', models.CharField(max_length=1)),
                ('alternativas', models.ManyToManyField(to='curso.alternativa')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'db_table': 'questao',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracao', models.TimeField(blank=True, null=True)),
                ('questoes', models.ManyToManyField(to='curso.questao')),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
                'db_table': 'prova',
            },
        ),
    ]
