# Generated by Django 4.1.7 on 2023-06-25 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0016_alternativa_alter_acessocursousuario_data_termino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='prova',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.prova'),
        ),
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 17, 54, 28, 656554)),
        ),
        migrations.AlterField(
            model_name='solicitarcurso',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 17, 54, 28, 656554)),
        ),
    ]
