# Generated by Django 4.1.7 on 2023-06-29 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0017_curso_prova_alter_acessocursousuario_data_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 0, 46, 28, 64935)),
        ),
        migrations.AlterField(
            model_name='solicitarcurso',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 0, 46, 28, 64935)),
        ),
    ]
