# Generated by Django 4.1.7 on 2023-06-30 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0019_alter_acessocursousuario_data_termino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='resposta',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='selecionada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 3, 20, 41, 250997)),
        ),
        migrations.AlterField(
            model_name='solicitarcurso',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 3, 20, 41, 251997)),
        ),
    ]
