# Generated by Django 4.1.7 on 2023-06-30 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0020_remove_questao_resposta_alternativa_selecionada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 13, 43, 50, 744502)),
        ),
        migrations.AlterField(
            model_name='prova',
            name='duracao',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True),
        ),
        migrations.AlterField(
            model_name='solicitarcurso',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 13, 43, 50, 744502)),
        ),
    ]
