# Generated by Django 4.1.7 on 2023-07-03 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0022_alter_acessocursousuario_data_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 23, 23, 37, 546541)),
        ),
        migrations.AlterField(
            model_name='acessocursousuario',
            name='quantidade_assitido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitarcurso',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 23, 23, 37, 546541)),
        ),
    ]
