# Generated by Django 4.1.7 on 2023-07-03 03:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0024_alter_acessocursousuario_data_termino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 0, 12, 51, 310719)),
        ),
        migrations.AlterField(
            model_name='solicitarcurso',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 0, 12, 51, 310719)),
        ),
        migrations.CreateModel(
            name='VideoAssistido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.video')),
            ],
            options={
                'verbose_name': 'video assistido',
                'verbose_name_plural': 'videos assistido',
                'db_table': 'video assistido',
            },
        ),
    ]
