# Generated by Django 4.1.7 on 2023-07-03 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0025_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 0, 19, 10, 763767)),
        ),
        migrations.RemoveField(
            model_name='acessocursousuario',
            name='quantidade_assitido',
        ),
        migrations.AlterField(
            model_name='solicitarcurso',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 0, 19, 10, 764768)),
        ),
        migrations.AddField(
            model_name='acessocursousuario',
            name='quantidade_assitido',
            field=models.ManyToManyField(blank=True, to='curso.videoassistido'),
        ),
    ]
