# Generated by Django 4.1.7 on 2023-07-03 19:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0027_alter_acessocursousuario_data_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessocursousuario',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 16, 49, 1, 669646)),
        ),
        migrations.AlterField(
            model_name='solicitarcurso',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 16, 49, 1, 669646)),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2023, 7, 3, 16, 49, 1, 670675))),
                ('status_prova', models.BooleanField()),
                ('procentagem', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
            options={
                'verbose_name': 'historico',
                'verbose_name_plural': 'historicos',
                'db_table': 'historico',
            },
        ),
    ]
